#!/bin/sh
ACTION=${1:-usage}
SUBJECT=${2:-screen}
FILE=${3:-$(xdg-user-dir PICTURES)/$(date +'Grimshot %Y-%m-%d %H-%M-%S.png')}
if [ $ACTION = "usage" ] ; then
  echo "Usage:"
  echo "  grimshot copy|save win|screen|area [FILE]"
  exit
fi

if [ $SUBJECT = "area" ] ; then
  GEOM=$(slurp -d)
  GEOM="-g \"$GEOM\""
  WHAT="Area"
elif [ $SUBJECT = "win" ] ; then
  GEOM=`swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .rect | "\(.x),\(.y) \(.width)x\(.height)"'`
  GEOM="-g \"$GEOM\""
  APP_ID=`swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .app_id'`
  WHAT="$APP_ID window"
elif [ $SUBJECT = "screen" ] ; then
  WHAT="Screen"
else
  die "Unknown subject to take a screen shot from" $SUBJECT
fi

if [ $ACTION = "copy" ] ; then
  TMP=${TMPDIR:-/tmp}/grim-$USER-data
  TITLE="Screenshot"
  MESSAGE="$WHAT copied to buffer"
  grim $GEOM $TMP
  xclip -selection clipboard -t image/png < $TMP
  wl-copy --type image/png < $TMP
  rm $TMP
  OK=true
else
  TITLE="Screenshot of $SUBJECT"
  MESSAGE=$(basename "$FILE")
  CMD="grim $GEOM \"$FILE\""
  sh -c "$CMD"
  if [ $? -eq 0 ]; then
    OK=true
  else
    OK=false
  fi
fi

if $OK ; then
  notify-send -a grimshot "$TITLE" "$MESSAGE"
else
  notify-send -u critical -a grimshot "Screenshot" "Error taking screenshot with grim"
fi
