#!/bin/sh
ACTION=${1:-usage}
SUBJECT=${2:-screen}
FILE=${3:-$(xdg-user-dir PICTURES)/$(date +'Grimshot %Y-%m-%d %H-%M-%S.png')}
if [ $ACTION = "usage" ] ; then
  echo "Usage:"
  echo "  grimshot copy|save win|screen|area [FILE]"
  exit
fi
function notify() {
  CMD="notify-send -t 3000 -a grimshot $*"
  sh -c "$CMD"
}

function notifyOk() {
  TITLE=${2:-"Screenshot"}
  MESSAGE=${1:-"OK"}
  notify "\"$TITLE\"" "\"$MESSAGE\""
}
function notifyError() {
  TITLE=${2:-"Screenshot"}
  MESSAGE=${1:-"Error taking screenshot with grim"}
  notify -u critical "\"$TITLE\"" "\"$MESSAGE\""
}

function die() {
  MSG=${1:-Bye}
  echo "Dead: $MSG"
  notify-send -u critical -a grimshot "Screenshot" "Dead: $MSG"
  exit -1
}

if [ $SUBJECT = "area" ] ; then
  GEOM=$(slurp -d)
  GEOM="-g \"$GEOM\""
  WHAT="Area"
elif [ $SUBJECT = "win" ] ; then
  GEOM=`swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .rect | "\(.x),\(.y) \(.width)x\(.height)"'`
  GEOM="-g \"$GEOM\""
  APP_ID=`swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .app_id'`
  WHAT="$APP_ID window"
elif [ $SUBJECT = "screen" ] ; then
  GEOM=""
  WHAT="Screen"
else
  die "Unknown subject to take a screen shot from" $SUBJECT
fi

if [ $ACTION = "copy" ] ; then
  TMP=${TMPDIR:-/tmp}/grim-$USER-data.png
  CMD="grim $GEOM $TMP"
  sh -c "$CMD" || die "Unable to take screenshot"
  wl-copy --type image/png < $TMP  || die
  rm $TMP
  notifyOk "$WHAT copied to buffer"
else
  CMD="grim $GEOM \"$FILE\""
  sh -c "$CMD"
  if [ $? -eq 0 ]; then
    TITLE="Screenshot of $SUBJECT"
    MESSAGE=$(basename "$FILE")
    notifyOk "$MESSAGE" "$TITLE"
  else
    notifyError "Error taking screenshot with grim"
  fi
fi

