#!/bin/sh
PID=/tmp/$USER-sway-pavucontrol.pid
if [ -f "$PID" ]; then
   kill `cat $PID`
   rm $PID
else 
   #GDK_BACKEND=x11 GDK_SCALE=2 GDK_DPI_SCALE=0.5 pavucontrol -t 1 --class pavuFloat &
   GDK_BACKEND=x11 pavucontrol -t 1 --class pavuFloat &
   echo $! > $PID
fi
